CREATE TABLE BankAccounts(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IBAN NVARCHAR(MAX) NOT NULL,
	Balance decimal(18,2) NOT NULL,
	Currency NVARCHAR(MAX) NOT NULL,
	PersonId NVARCHAR(450) NOT NULL,

	FOREIGN KEY (PersonId)
	REFERENCES AspNetUsers(Id)
)


CREATE TABLE BankCards(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Firstname NVARCHAR(MAX) NOT NULL,
	Lastname NVARCHAR(MAX) NOT NULL,
	CardNumber NVARCHAR(MAX) NOT NULL,
	ExpirationDate DATE NOT NULL,
	CVV NVARCHAR(MAX) NOT NULL,
	PinCode NVARCHAR(MAX) NOT NULL,
	PersonId NVARCHAR(450) NOT NULL,

	FOREIGN KEY (PersonId)
	REFERENCES AspNetUsers(Id)
)


CREATE TABLE AccountTransactions(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Amount decimal(18,2) NOT NULL,
	Currency NVARCHAR(MAX) NOT NULL,
	TransactionDate DATE NOT NULL,
	FromAccountId INT NOT NULL,
	ToAccountId INT NOT NULL,
	FOREIGN KEY (FromAccountId)
	REFERENCES BankAccounts(Id),

	FOREIGN KEY (ToAccountId)
	REFERENCES BankAccounts(Id)
)
