CREATE TABLE BankAccounts(
	BankAccountId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IBAN VARCHAR(34) unique NOT NULL CHECK (LEN(IBAN) BETWEEN 15 AND 34),
	Balance decimal(18,2) NOT NULL CHECK (Balance >= 0),
	Currency NVARCHAR(3) NOT NULL CHECK (Currency IN ('USD', 'EUR', 'GEL')),
	PersonId NVARCHAR(450) NOT NULL,

	FOREIGN KEY (PersonId)
	REFERENCES AspNetUsers(Id) ON DELETE CASCADE,

	INDEX IX_BankAccounts_IBAN NONCLUSTERED (IBAN)
)
